#!/bin/bash

unset tbfrag
unset output
while [[ "$1" != "" ]]
do
    case "$1" in
    "-o") output="$2"; shift;;
    "--tbfrag") tbfrag="$2"; shift;;
    *) echo "unknown argument $1" >&2; exit 1;;
    esac
    shift
done

if [[ "$tbfrag" == "" ]]
then
    echo "no argument --tbfrag passed"
    exit 2
fi

if [[ "$output" == "" ]]
then
    echo "no argument -o passed"
    exit 2
fi

cat >$output <<EOF
#define TBFRAG "${tbfrag}"
EOF
