#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# See LICENSE for license details.
#
#  hammer-vlsi
#  CLI script - by default, it just uses the default CLIDriver.
#

from hammer_vlsi import CLIDriver

if __name__ == '__main__':
    CLIDriver().main()
