#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
#  hammer-vlsi
#  CLI script - by default, it just uses the default CLIDriver.
#
#  See LICENSE for licence details.

from hammer_vlsi import CLIDriver

if __name__ == '__main__':
    CLIDriver().main()
