#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  Older versions of readlink, like readlink 8.4, don't support multiple
#  arguments to readlink.
#  This script is meant to emulate that behaviour on those systems.
#  Usage:
#  readlink_array foo bar baz == readlink -f foo bar baz
#
#  See LICENSE for licence details.

from __future__ import print_function
import os
import subprocess
import sys

"""Note: We also monkey-patch subprocess for python 2.6 to
give feature parity with later versions.
https://stackoverflow.com/a/34055481
"""
try:
    from subprocess import STDOUT, check_output, CalledProcessError
except ImportError:  # pragma: no cover
    # python 2.6 doesn't include check_output
    # monkey patch it in!
    import subprocess
    STDOUT = subprocess.STDOUT

    def check_output(*popenargs, **kwargs):
        if 'stdout' in kwargs:  # pragma: no cover
            raise ValueError('stdout argument not allowed, '
                             'it will be overridden.')
        process = subprocess.Popen(stdout=subprocess.PIPE,
                                   *popenargs, **kwargs)
        output, _ = process.communicate()
        retcode = process.poll()
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
            raise subprocess.CalledProcessError(retcode, cmd,
                                                output=output)
        return output
    subprocess.check_output = check_output

    # overwrite CalledProcessError due to `output`
    # keyword not being available (in 2.6)
    class CalledProcessError(Exception):

        def __init__(self, returncode, cmd, output=None):
            self.returncode = returncode
            self.cmd = cmd
            self.output = output

        def __str__(self):
            return "Command '%s' returned non-zero exit status %d" % (
                self.cmd, self.returncode)
    subprocess.CalledProcessError = CalledProcessError

def main(args):
  # Pop the script name.
  arg0 = args.pop(0)

  if len(args) == 0:
    print(arg0 + ": missing operand", file=sys.stderr)
    return 1

  for arg in sys.argv:
    # Run 'readlink -f' on each argument, and print the result.
    print(subprocess.check_output(["readlink", "-f", arg]).strip())

  return 0

if __name__ == '__main__':
  sys.exit(main(sys.argv))
