# Specify clock signals
vlsi.inputs.clocks: [
  {name: "clock", period: "5ns", uncertainty: "0.1ns"}
]

# Tool options.
vlsi.inputs.placement_constraints:
  - path: "pass"
    type: toplevel
    x: 0
    y: 0
    width: 10
    height: 10
    margins:
      left: 0
      right: 0
      top: 0
      bottom: 0

vlsi.inputs.pin_mode: generated
vlsi.inputs.pin.generate_mode: semi_auto
vlsi.inputs.pin.assignments: [
  {pins: "*", layers: ["M5"], side: "bottom"}
]

vlsi.inputs.delays: [
  {name: "in", clock: "clock", delay: "1", direction: "input"},
  {name: "out", clock: "clock", delay: "2", direction: "output"}
]


# SRAM Compiler compiler options
vlsi.core.sram_generator_tool: "hammer.technology.asap7.sram_compiler"
