# Post-PAR Simulation

sim.inputs:
  top_module: pass
  tb_dut: pass_0
  tb_name: "pass_tb"
  input_files: ['src/pass_tb.v']
  input_files_meta: append
  level: "par"
  options: ['-timescale=1ns/10ps']
  options_meta: append
  timing_annotated: false

