version: 2
formats: all

# Set Python version & poetry tools
build:
  os: ubuntu-22.04
  tools:
    python: '3.10'
  jobs:
    post_install:
      - pip install poetry myst-parser
      - poetry config virtualenvs.create false
      - poetry install
      - python3 -c "from hammer.tech import TechJSON; print(TechJSON.schema_json(indent=2))" > doc/Technology/schema.json

# Build documentation with Sphinx
sphinx:
  configuration: doc/conf.py
