version: 2
formats: all

# Set Python version & poetry tools
build:
  os: ubuntu-latest
  tools:
    python: '3.10'
  jobs:
    post_install:
      - pip install poetry myst-parser
      - poetry config virtualenvs.create false
      - poetry install

# Build documentation with Sphinx
sphinx:
  configuration: doc/conf.py
