#!/bin/bash
# Copyright 2017 Edward Wang <edward.c.wang@compdigitec.com>
# Entry point to PLSI that wraps the Makfile invocation to handle
# various loose ends (e.g. using pre-built tool binaries).

# PLSI_MAKEFLAGS should contain all extra arguments to make.
# This is required because some flags critical to PLSI like -o are not
# supported via MAKEFLAGS.

# PLSI_MAKEFILES is a list (string separated by spaces) of all the extra
# Makefiles to include via -f before running the main PLSI makefile.

make_cmd="make $PLSI_MAKEFLAGS $(./src/tools/get-makefiles-args $PLSI_MAKEFILES) -f Makefile.plsi $@"
echo "Make command to be executed: $make_cmd"
#$make_cmd
