#!/bin/bash

unset sbt
unset src_dir
unset out_dir
while [[ "$1" != "" ]]
do
    case "$1" in
    "--sbt") sbt="$2";;
    "--srcdir") src_dir="$2";;
    "--outdir") out_dir="$2";;
    *) echo "Unknown argumest $1"; exit 1;;
    esac
    shift
    shift
done

cd "$src_dir"
cat /dev/null | "$sbt" "run $out_dir"
