# This file is dynamically-generated; do not edit this file.
# TCL fragment to set some paths.

set_param board.repoPaths [list ""];
set scriptdir {{ work_dir }};
set dcpdir "";
set srcmainverilogfile {{ verilog_files }};
set srcmainverilogfiles {{ verilog_files }};
