#!/bin/bash
# Run the Vivado synthesis.

# setup environment variables
source {{ env_setup_script }}

# execute vivado
cd {{ work_dir }}
{{ vivado_cmd }} -nojournal -mode batch -source board.tcl -source paths.tcl -source project.tcl \
                 -source prologue.tcl -source init.tcl -source syn.tcl
