#!/bin/bash

max_threads=999
while [[ "$1" != "--" ]]
do
    case "$1" in
    --max-threads=*)
      max_threads="$(echo -e "$max_threads\\n$(echo "$1" | cut -d= -f2-)" | sort | head -n1)"
      ;;
    esac
    shift
done
shift

export PLSI_SCHEDULER_MAX_THREADS="$(cat /proc/cpuinfo | grep ^processor | wc -l)"
if [[ "$PLSI_SCHEDULER_MAX_THREADS" > $max_threads ]]
then
    PLSI_SCHEDULER_MAX_THREADS=$max_threads
fi

exec "$@"
