# Copyright 2016 Palmer Dabbelt <palmer@dabbelt.com>

CHIP_TOP = $(SYSTEM_TOP)

OBJ_CHIP_RTL_V = $(OBJ_SYSTEM_RTL_V)
OBJ_CHIP_RTL_C = $(OBJ_SYSTEM_RTL_C)
OBJ_CHIP_RTL_H = $(OBJ_SYSTEM_RTL_H)
OBJ_CHIP_RTL_O = $(OBJ_SYSTEM_RTL_O)
OBJ_CHIP_RTL_I = $(OBJ_SYSTEM_RTL_I)
