#!/bin/bash

set -ex

unset innovus
unset tf
unset output
while [[ "$1" != "" ]]
do
    case "$1" in
    --innovus) innovus="$2"; shift;;
    --tf) tf="$2"; shift;;
    --output) output="$2"; shift;;
    *) echo "Unsupported argument $1" >&2; exit 1;;
    esac
    shift
done

tempdir="$(mktemp -d /tmp/plsi-tf2lef.XXXXXX)"
trap "rm -rf $tempdir" EXIT

cat > $tempdir/run.tcl <<EOF
set enc_source_verbose_output debug
generateLef -techFile $tf $output
exit
EOF
cat $tempdir/run.tcl

cd $tempdir
$innovus -no_gui -files run.tcl |& tee log

if test ! -f "$output"
then
    echo "No output produced" >&2
    exit 1
fi
