#!/usr/bin/python

import sys
import argparse
import json

def parse_args(args):
  parser = argparse.ArgumentParser(description = 'generate macros')
  parser.add_argument('--conf', type=str, required=True,
    help="""macro conf file from FIRRTL (e.g. <design>.conf)""")
  parser.add_argument('--json', type=str, required=True,
    help="""output JSON file""")

  res = parser.parse_args(args)
  return res.conf, res.json

def read_conf(filename):
  srams = list()
  with open (filename) as f:
    for line in f:
      sram = {"type" : "sram"}
      tokens = line.split()
      for i in xrange(0, len(tokens), 2):
        field = tokens[i]
        value = tokens[i+1]
        if field == 'name':
          sram[field] = value
        elif field == 'depth':
          sram[field] = int(value)
        elif field == 'width':
          sram[field] = int(value)
        elif field == 'ports':
          sram[field] = value.split(',')
        elif field == 'mask_gran':
          sram[field] = int(value)
        else:
          sys.exit('%s: unknown argument %s' % (sys.argv[0], field))

      srams.append(sram) 

  return srams

def expand_ports(srams):
  for sram in srams:
    eports = list()
    for i, port in enumerate(sram['ports']):
      eport = dict()
      masked = False

      if port[0] == 'm':
        masked = True
        port = port[1:]

      if port == 'rw':
        eport["clock port name"] = "RW%d_clk" % (i)
        eport["output port name"] = "RW%d_rdata" % (i)
        eport["input port name"] = "RW%d_wdata" % (i)
        eport["address port name"] = "RW%d_addr" % (i)
        eport["chip enable port name"] = "RW%d_en" % (i)
        eport["write enable port name"] = "RW%d_wmode" % (i)
        if masked:
          eport["mask port name"] = "RW%d_wmask" % (i)
          eport["mask granularity"] = sram["mask_gran"]

      elif port == 'read':
        eport["clock port name"] ="R%d_clk" % (i)
        eport["output port name"] ="R%d_data" % (i)
        eport["address port name"] ="R%d_addr" % (i)
        eport["chip enable port name"] ="R%d_en" % (i)

      elif port == 'write':
        eport["clock port name"] = "W%d_clk" % (i)
        eport["input port name"] = "W%d_data" % (i)
        eport["address port name"] = "W%d_addr" % (i)
        eport["chip enable port name"] = "W%d_en" % (i)
        if masked:
          eport["mask port name"] = "W%d_wmask" % (i)
          eport["mask granularity"] = sram["mask_gran"]

      eports.append(eport)

    sram['ports'] = eports

  return

if __name__ == '__main__':
  conf_filename, json_filename = parse_args(sys.argv[1:])

  srams = read_conf(conf_filename)

  expand_ports(srams)

  with open(json_filename, 'w') as f:
    f.write(json.dumps(srams, indent=2, separators=(',', ': ')))
