name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Background work
      description: Yes, I searched the following areas for a prior solution and this is the right place to post it.
      options:
        - label: Yes, I searched the [documentation](https://hammer-vlsi.readthedocs.io/)
          required: true
        - label: Yes, I searched in the [Support (Q&A)](https://github.com/ucb-bar/hammer/discussions/categories/support-q-a) section of the Discussions and read the [posting guidelines](https://github.com/ucb-bar/hammer/discussions/717)
          required: true
        - label: Yes, I searched [prior issues](https://github.com/ucb-bar/hammer/issues?q=)
          required: true
        - label: This issue is specific to Hammer, i.e., does not belong in a plugin repository instead
          required: true
        - label: My report does not contain sensitive info (e.g., PDK information under NDA)
          required: true
        - label: (If applicable) Yes, I searched the [Chipyard documentation](https://chipyard.readthedocs.io/)
        - label: (If applicable) Yes, I searched the [Chipyard mailing list](https://groups.google.com/forum/#!forum/chipyard)
        - label: (If applicable) Yes, I searched the [Chipyard issues](https://github.com/ucb-bar/chipyard/issues?q=)

  - type: textarea
    attributes:
      label: Hammer version and plugin hashes
      description: Repository and external plugin versions for reproducability
      placeholder: Version + Hash
      value: |
        Release: 1.0.0
        Hash: a1b2c3
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other Setup
      description: Any setup that is relevant
      placeholder: Other setup
      value: |
        Ex: OS information, steps taken, documentation followed, etc.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expect to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other Information
      description: Other information needed to understand/reproduce the issue.
      placeholder: |
        Log files (remember to sanitize it of any sensitive info)
        Input Hammer IR
        Related issues/discussions
        Suggestions on fixes
        Tip: you can drag files into this text area
    validations:
      required: false
