blank_issues_enabled: true
contact_links:
  - name: Hammer Discussions
    url: https://github.com/ucb-bar/hammer/discussions
    about: Please use this for general support and feature talk.
  - name: Chipyard Mailing List
    url: https://groups.google.com/forum/#!forum/chipyard
    about: If you are using Chipyard, this may be the more applicable place to ask/answer questions.
