#!/usr/bin/env python3

import argparse
parser = argparse.ArgumentParser()
parser.add_argument("-o", "--output", dest="output", required=True)
parser.add_argument("-i", "--input", dest="input", required=True)
parser.add_argument("-c", "--config", dest="config", required=True)
args = parser.parse_args()

import json
with open(args.input) as f:
	techfile = json.load(f)

with open(args.config) as f:
	config = json.load(f)

if not "scenerios" in config:
	print("No scenerios provided in PLSI configuration")
	exit(1)

of = open(args.output, "w+")

new_libraries = []
for library in techfile["libraries"]:
	a_match = False
	for scenerio in config["scenerios"]:
		matched = True
		for key in scenerio:
			if key in library:
				if library[key] != scenerio[key]:
					matched = False
		if matched:
			a_match = True

	if a_match:
		new_libraries.append(library)

techfile["libraries"] = new_libraries

of.write(json.dumps(techfile))

of.close
