#!/usr/bin/env python3

import argparse
parser = argparse.ArgumentParser()
parser.add_argument("-o", "--output", dest="output", required=True)
parser.add_argument("-i", "--input", dest="input", required=True)
args = parser.parse_args()

import json
with open(args.input) as f:
        techfile = json.load(f)

import subprocess

of = open(args.output, "w+")
of.write("[\n")

for library in techfile["libraries"]:
	if "provides" in library:
		for macro in library["provides"]:
			print(macro)
			if (macro["type"] == "sram"):
				of.write(json.dumps(macro))
				of.write(",\n")
	if "provide script" in library:
		# FIXME: OBJ_TECH_DIR shouldn't be hard-coded here
		p = subprocess.check_output([library["provide script"], "obj/technology/saed32/extracted/{0}".format(library["verilog file"])]).decode("utf-8")
		macros = json.loads(p)
		for macro in macros:
			print(macro)
			if (macro["type"] == "sram"):
				of.write(json.dumps(macro))
				of.write(",\n")
		

of.write("]\n")

of.close
