#!/bin/bash

v=()
while [[ "$1" != "" ]]
do
    case "$1" in
    *_lvt.v)
      vt="lvt"
      v+=("$1")
    ;;
    */saed32nm.v)
      vt="rvt"
      v+=("$1")
    ;;
    *_hvt.v)
      vt="hvt"
      v+=("$1")
    ;;
    *) echo "unknown argument $1" >&2; exit 1;;
    esac

    shift
done

if test ! -f "$v"
then
    echo "Unable to open Verilog stdcell library: '$v'" >&2
    exit 1
fi

cat <<EOF
[
EOF

cat "$v" | grep "^module DCAP" | while read line
do
    cell="$(echo "$line" | sed 's@module \([A-Za-z0-9_]*\).*@\1@')"
    cat <<EOF
  {
    "type": "metal filler cell",
    "vt": "$vt",
    "name": "$cell"
  },
EOF
done

cat "$v" | grep "^module DHFILL" | while read line
do
    cell="$(echo "$line" | sed 's@module \([A-Za-z0-9_]*\).*@\1@')"
    cat <<EOF
  {
    "type": "filler cell",
    "vt": "$vt",
    "name": "$cell"
  },
EOF
done

cat "$v" | grep "^module SHFILL" | while read line
do
    cell="$(echo "$line" | sed 's@module \([A-Za-z0-9_]*\).*@\1@')"
    cat <<EOF
  {
    "type": "filler cell",
    "vt": "$vt",
    "name": "$cell"
  },
EOF
done

cat <<EOF
  {
    "type": "stdcells",
    "vt": "$vt"
  }
]
EOF
