#!/bin/bash

set -e

unset family
while [[ "$1" != "" ]]
do
    case "$1" in
    --family) family="$2"; shift;;
    *) echo "Unknown argument $1"; exit 1;;
    esac
    shift
done

echo "["

for width in $(seq 4 512)
do
    for depth in $(echo 16 32 64 128)
    do
        case "$family" in
        "mc-1rw")
        cat <<EOF
  {
    "type": "sram",
    "name": "SRAM${depth}x${width}single_32",
    "width": ${width},
    "depth": ${depth},
    "family": "mc-1rw",
    "ports": [
      {
        "address port name": "A",
        "address port polarity": "active high",
        "clock port name": "CE",
        "clock port polarity": "positive edge",
        "write enable port name": "WEB",
        "write enable port polarity": "active low",
        "read enable port name": "OEB",
        "read enable port polarity": "active low",
        "chip enable port name": "CSB",
        "chip enable port polarity": "active low",
        "output port name": "O",
        "output port polarity": "active high",
        "input port name": "I",
        "input port polarity": "active high"
      }
    ]
  },
EOF
        ;;

        "mc-2rw")
        cat << EOF
  {
    "type": "sram",
    "name": "SRAM${depth}x${width}dual_32",
    "width": ${width},
    "depth": ${depth},
    "family": "mc-2rw",
    "ports": [
       {
        "address port name": "A1",
        "address port polarity": "active high",
        "clock port name": "CE1",
        "clock port polarity": "positive edge",
        "write enable port name": "WEB1",
        "write enable port polarity": "active low",
        "read enable port name": "OEB1",
        "read enable port polarity": "active low",
        "chip enable port name": "CSB1",
        "chip enable port polarity": "active low",
        "output port name": "O1",
        "output port polarity": "active high",
        "input port name": "I1",
        "input port polarity": "active high"
      },
      {
        "address port name": "A2",
        "address port polarity": "active high",
        "clock port name": "CE2",
        "clock port polarity": "positive edge",
        "write enable port name": "WEB2",
        "write enable port polarity": "active low",
        "read enable port name": "OEB2",
        "read enable port polarity": "active low",
        "chip enable port name": "CSB2",
        "chip enable port polarity": "active low",
        "output port name": "O2",
        "output port polarity": "active high",
        "input port name": "I2",
        "input port polarity": "active high"
      }
    ]
  },
EOF
        ;;
        *) echo "Unknown family $family" >&2; exit 1;;
        esac
    done
done

echo '{"type": "none"}]'
