#!/bin/bash

# See vivado.tech.json
# TODO: build/replace _plsi_tech_vivado_prebuilt_sram_64b_4096

set -e

cat << EOF
[

{
  "type": "sram",
  "name": "_plsi_tech_vivado_prebuilt_sram_32b_4096",
  "width": 32,
  "depth": 4096,
  "family": "1rw",
  "ports": [
    {
      "address port name": "addr",
      "address port polarity": "active high",
      "clock port name": "clock",
      "clock port polarity": "positive edge",
      "input port name": "data_in",
      "input port polarity": "active high",
      "write enable port name": "write_enable",
      "write enable port polarity": "active low",
      "output port name": "data_out",
      "output port polarity": "active high",
      "mask port name": "mask",
      "mask port polarity": "active high",
      "mask granularity": 1
    }
  ]
},
{
  "type": "sram",
  "name": "_plsi_tech_vivado_prebuilt_sram_32b_2048",
  "width": 32,
  "depth": 2048,
  "family": "1rw",
  "ports": [
    {
      "address port name": "addr",
      "address port polarity": "active high",
      "clock port name": "clock",
      "clock port polarity": "positive edge",
      "input port name": "data_in",
      "input port polarity": "active high",
      "write enable port name": "write_enable",
      "write enable port polarity": "active low",
      "output port name": "data_out",
      "output port polarity": "active high",
      "mask port name": "mask",
      "mask port polarity": "active high",
      "mask granularity": 1
    }
  ]
},
{
  "type": "sram",
  "name": "_plsi_tech_vivado_prebuilt_sram_64b_4096",
  "width": 64,
  "depth": 409600,
  "family": "2rw",
  "ports": [
    {
      "address port name": "AB",
      "address port polarity": "active high",
      "clock port name": "CLKR",
      "clock port polarity": "positive edge",
      "read enable port name": "REB",
      "read enable port polarity": "active low",
      "output port name": "Q",
      "output port polarity": "active high"
    },
    {
      "address port name": "AA",
      "address port polarity": "active high",
      "clock port name": "CLKW",
      "clock port polarity": "positive edge",
      "input port name": "D",
      "input port polarity": "active high",
      "write enable port name": "WEB",
      "write enable port polarity": "active low",
      "mask port name": "BWEB",
      "mask port polarity": "active low",
      "mask granularity": 1
    }
  ]
}

]
EOF
