#!/bin/bash

set -e

verilog=()
verilog_h=()
c=()
h=()
o=()
output=""
mode=""
vcs=""
top=""
include=()
i=()
cc=()
debug_flags=()
tbvfrag=""
ucli_build_flags=()
ucli_run_flags=()
while [[ "$1" != "" ]]
do
    case "$1" in
    */verilator.h) ;;
    */emulator.cc) ;;
    *.v) verilog+=("$1");;
    *.vh) verilog_h+=("$1");;
    *.c) c+=("$1");;
    *.h) h+=("-CC \"-include$1\"");;
    *.c++) c+=("$1");;
    *.cxx) c+=("$1");;
    *.cc) c+=("$1");;
    *.so) o+=("$1");;
    */bin/vcs) vcs="$1";;
    */plsi-include.stamp) i+=("-CC \"-I$(dirname "$1")\"");;
    *.tb.vfrag) tbvfrag="+define+TBVFRAG+\\\"$(basename $1)\\\"";;
    *.ucli) ucli_run_flags+=("$1");;
    *.tab) ucli_build_flags+=("-P" "$1");;
    "-o") output="$2"; shift;;
    "--level") level="$2"; shift;;
    "--mode") mode="$2"; shift;;
    "--top") top="$2"; shift;;
    $0) ;;
    *) echo "Unknown argument $1" >&2; exit 2;;
    esac
    shift
done

rm -rf "$output".daidir "$output".vcs_build_dir
mkdir -p "$output".vcs_build_dir

cat >$output.enter <<EOF
export VCS_HOME="$(dirname $(dirname "$vcs"))"
export PATH="\$VCS_HOME/bin:\$PATH"
export MGLS_LICENSE_FILE="$MGLS_LICENSE_FILE"
export SNPSLMD_LICENSE_FILE="$SNPSLMD_LICENSE_FILE"
EOF
source $output.enter

if [[ "$mode" == "debug" ]]
then
    debug_flags+=("+define+DEBUG")
fi

if [[ "$vcs" == "" ]]
then
    echo "Unable to find VCS, pass it on the command line"
    exit 1
fi

cd "$output".vcs_build_dir
set -x
$vcs -full64 \
    -quiet \
    -notice -line -error=PCWM-L \
    -timescale=1ns/10ps \
    -sverilog \
    -debug_pp \
    +rad \
    +v2k \
    +vcs+lic+wait \
    +vcs+initreg+random \
    ${debug_flags[@]} \
    ${ucli_build_flags[@]} \
    -CC "-std=c++11" \
    $tbvfrag \
    ${h[*]} \
    ${i[*]} \
    ${verilog_h[*]} \
    ${verilog[*]} \
    ${c[*]} \
    ${o[*]} \
    -o "$output"

cat ${ucli_run_flags[@]} - >$output.ucli <<EOF
run
quit
EOF
