#!/bin/bash

unset output
unset VCS_TARGET_CAPS
unset VCS_TARGET_LOWER
unset VTYPE
while [[ "$1" != "" ]]
do
    case "$1" in
    --lower) VCS_TARGET_LOWER="$2"; shift;;
    --upper) VCS_TARGET_CAPS="$2"; shift;;
    --vtype) VTYPE="$2"; shift;;
    --output) output="$2"; shift;;
    *) echo "unknown argument $1"; exit 1;;
    esac
    shift
done

cat >"$output" <<EOF
\$(CHECK_${VCS_TARGET_CAPS}_DIR)/%.out: \$(${VCS_TARGET_CAPS}_SIMULATOR_ADDON)/tools/run-simulator \$(OBJ_${VCS_TARGET_CAPS}_DIR)/simulator-ndebug \$(CMD_PTEST)
	mkdir -p \$(dir \$@)
	\$(SCHEDULER_CMD) --max-threads=1 -- \$(CMD_PTEST) --test \$(abspath \$(${VCS_TARGET_CAPS}_SIMULATOR_ADDON)/tools/run-simulator) --out \$@ --args \$(abspath \$^)

\$(CHECK_${VCS_TARGET_CAPS}_DIR)/%.trace-out \$(CHECK_${VCS_TARGET_CAPS}_DIR)/%.vpd: \$(${VCS_TARGET_CAPS}_SIMULATOR_ADDON)/tools/run-simulator \$(OBJ_${VCS_TARGET_CAPS}_DIR)/simulator-debug \$(CMD_PTEST)
	mkdir -p \$(dir \$@)
	\$(SCHEDULER_CMD) --max-threads=1 -- \$(CMD_PTEST) --test \$(abspath \$(${VCS_TARGET_CAPS}_SIMULATOR_ADDON)/tools/run-simulator) --out \$@ --args \$(abspath \$^) --vpd \$@.vpd

ifeq (\$(${VCS_TARGET_CAPS}_TOP),)
\$(error ${VCS_TARGET_CAPS}_TOP must be defined)
endif

ifeq (\$(OBJ_${VCS_TARGET_CAPS}_${VTYPE}_V),)
\$(error OBJ_${VCS_TARGET_CAPS}_${VTYPE}_V must be defined)
endif

ifeq (\$(VCS_BIN),)
\$(error VCS_BIN must be defined)
endif

\$(info \$(OBJ_${VCS_TARGET_CAPS}_${VTYPE}_V))
\$(patsubst %,\$(OBJ_${VCS_TARGET_CAPS}_DIR)/simulator-%,ndebug debug): \\
		\$(OBJ_${VCS_TARGET_CAPS}_${VTYPE}_V) \\
		\$(OBJ_${VCS_TARGET_CAPS}_SIM_FILES) \\
		\$(OBJ_${VCS_TARGET_CAPS}_SIM_MACRO_FILES) \\
		\$(VCS_BIN) \\
		\$(${VCS_TARGET_CAPS}_SIMULATOR_ADDON)/tools/build-simulator
	mkdir -p \$(dir \$@)
	+\$(SCHEDULER_CMD) -- \$(abspath \$(${VCS_TARGET_CAPS}_SIMULATOR_ADDON)/tools/build-simulator) -o \$(abspath \$@) --top \$(${VCS_TARGET_CAPS}_TOP) --level ${VCS_TARGET_LOWER} --mode \$(patsubst simulator-%,%,\$(notdir \$@)) \$(abspath \$^)
EOF
