#!/bin/bash

set -e
set -x

unset simulator
unset debug
unset vpd
args=()
debug_args=()
while [[ "$1" != "" ]]
do
    case "$1" in
    */simulator-debug)
        simulator="$1"
        debug="true"
        ;;
    */simulator-ndebug)
        simulator="$1"
        debug="false"
        ;;
    */ptest) ;;
    --vpd) vpd="$2"; shift;;
    "$0") ;;
    *) args+=("$1");;
    esac
    shift
done

if [[ "$debug" == "true" ]]
then
    debug_args+=("+vcdplusfile=out.vpd")
fi

tempdir="$(mktemp -d /tmp/plsi-vcs-run.XXXXXX)"
trap "rm -rf $tempdir" EXIT

# FIXME: This is a fesvr problem: if your script doesn't start with a "+" then
# fesvr will stop parsing arguments and drop the RISC-V test binary.
cp "$simulator".ucli $tempdir/+run.ucli

cd $tempdir
cat /dev/null | \
    "$simulator" \
    -ucli -do +run.ucli \
    +ntb_random_seed_automatic \
    +max-cycles=10000000 \
    +vcs+initreg+random \
    ${debug_args[*]} \
    ${args[*]} |& tee $tempdir/log

if [[ "$debug" == "true" ]]
then
    mkdir -p "$(dirname "${vpd}")"
    mv out.vpd "${vpd}"
fi

# FIXME: This is Rocket Chip specific
set +e
grep FAILED $tempdir/log
if [[ "$?" != 1 ]]
then
   echo "FAILED found in log"
   exit 1
fi

grep "Assertion" $tempdir/log
if [[ "$?" != 1 ]]
then
    echo "Assertion found in log"
    exit 1
fi

grep "Error-" $tempdir/log
if [[ "$?" != 1 ]]
then
    echo "Error- found in log"
    exit 1
fi
