#!/bin/bash

unset simulator
unset debug
unset vpd
args=()
debug_args=()
while [[ "$1" != "" ]]
do
    case "$1" in
    */simulator-debug)
        simulator="$1"
        debug="true"
        ;;
    */simulator-ndebug)
        simulator="$1"
        debug="false"
        ;;
    */ptest) ;;
    --vpd) vpd="$2"; shift;;
    "$0") ;;
    *) args+=("$1");;
    esac
    shift
done

if [[ "$debug" == "true" ]]
then
    debug_args+=("+vcdplusfile=${vpd}")
fi

tempdir="$(mktemp -d /tmp/plsi-vcs-run.XXXXXX)"
trap "rm -rf $tempdir" EXIT

set -e
set -x
cat "$simulator".ucli /dev/null | \
    "$simulator" \
    -ucli \
    +ntb_random_seed_automatic \
    +max-cycles=600000 \
    +vcs+initreg+random \
    ${debug_args[*]} \
    ${args[*]} |& tee $tempdir/log

# FIXME: This is Rocket Chip specific
set +e
grep FAILED $tempdir/log
if [[ "$?" != 1 ]]
then
   echo "FAILED found in log"
   exit 1
fi
