#!/bin/bash

unset simulator
unset debug
unset vpd
args=()
while [[ "$1" != "" ]]
do
    case "$1" in
    */simulator-debug)
        simulator="$1"
        debug="true"
        ;;
    */simulator-ndebug)
        simulator="$1"
        debug="false"
        ;;
    */ptest) ;;
    --vpd) vpd="$2"; shift;;
    "$0") ;;
    *) args+=("$1");;
    esac
    shift
done

debug_args=()
if [[ "$debug" == "true" ]]
then
    debug_args+=("+vcdplusfile=${vpd}")
fi

set -e
set -x
"$simulator" ${debug_args[*]} ${args[*]}
