#!/bin/bash

unset output
unset tools_dir
unset CC
unset CXX
while [[ "$1" != "" ]]
do
    case $1 in
    "--output-dir") output="$2"; shift;;
    "--tools-dir") tools_dir="$2"; shift;;
    --cc) CC="$2" shift;;
    --cxx) CXX="$2"; shift;;
    *) echo "unknown argumente $1"; exit 1;;
    esac
    shift
done

export CC
export CXX
export RISCV="$output"

rm -rf "$RISCV"
cd "$tools_dir"
./build.sh || (find . -iname "build.log" | xargs tail; exit 1)
