# Copyright 2016 Palmer Dabbelt <palmer@dabbelt.com>

SOC_TOP = $(CORE_TOP)
SOC_SIM_TOP = $(CORE_SIM_TOP)

OBJ_SOC_RTL_V = $(OBJ_SOC_DIR)/$(SOC_TOP).v
OBJ_SOC_SIM_FILES = $(OBJ_CORE_SIM_FILES)
OBJ_SOC_SIM_MACRO_FILES = $(OBJ_CORE_SIM_MACRO_FILES)
OBJ_SOC_MACROS = $(OBJ_CORE_MACROS)
