#!/usr/bin/env python3

from parse import *
from math import ceil
from itertools import chain
from argparse import ArgumentParser
from functools import total_ordering

# Represents a single position, which itself is an offset from something else.
class Position:
  def __init__(self, macro, corner):
    self.macro = macro
    self.corner = corner

  def add_child(self, child):
    self.macro.add_child(child)

# Defines a constraint, which consists of two macro corners that must go together
class Constraint:
  def __init__(self, corner_to_move, fixed_corner, offset_x, offset_y, orientation):
    self.corner_to_move = corner_to_move
    self.fixed_corner = fixed_corner
    self.offset_x = offset_x
    self.offset_y = offset_y
    self.orientation = orientation

  def as_json(self):
    return '{"offset_x": "%s", "offset_y": "%s", "macro": "%s", "corner_on_macro_to_match": "%s", "anchor_to_%s": "%s", "corner_on_anchor_%s_to_match": "%s", "orientation": "%s"}' % (self.offset_x, self.offset_y, self.corner_to_move.macro.name, self.corner_to_move.corner, self.fixed_corner.macro.json_type(), self.fixed_corner.macro.name, self.fixed_corner.macro.json_type(), self.fixed_corner.corner, self.orientation)

# Sometimes I want to refer to a point-sized thing
class FixedPosition:
  def __init__(self, corner):
    self.corner = corner

  def tl(self):
    return self.corner
  def tr(self):
    return self.corner
  def bl(self):
    return self.corner
  def br(self):
    return self.corner

# Contains a single macro, along with some helper functions to parse the output
# of the macro list and to match heirarchies 
@total_ordering
class ParsedMacro:
  def __init__(self, str):
    p = parse("{} parent={} module={} width={} height={}", str)
    if p != None:
      p = p.fixed
      self.name = p[0]
      self.parent = p[1]
      self.module = p[2]
      self.width = float(p[3])
      self.height = float(p[4])
    else:
      p = parse("{} module={} top_left=({}, {}) bottom_right=({}, {})", str).fixed
      self.name = p[0]
      self.parent = None
      self.module = p[1]
      self.width = float(p[4]) - float(p[2])
      self.height = float(p[5]) - float(p[3])

  # This function matches both Chisel and DC's name mangling schemes to
  # determine if the name of this macro matches the supplied pattern.  Modules
  # in the heirarchy are delimated by "/" characters in the pattern, which can
  # match either "/" characters in the module name or "_" characters in the
  # module name (the "_" comes when DC ungroups a heirarchy).  Since Chisel
  # mangles instance names by adding "_%d" to the end of them, appending these to
  # the end of a module won't prevent a match.  Since macros are frequently
  # rolled up inside otherwise unnameable objects, any string of "T%d" at the
  # end of a module name won't reject a match.  Finally, since SRAM macros
  # almost always have to wrap the actual SRAM implementation, any "sram%d"
  # after the end of a pattern (and also after any "T%d" strings) won't reject a
  # match.
  def matches(self, pattern):
    print("matches(" + self.name + ", " + pattern + ")")
    if self.name == pattern:
      return True

    remaining_name = self.name.replace("__", "_")
    for module_pattern in pattern.split("/"):
      print("  checking " + remaining_name + " againist " + module_pattern + " (full pattern: " + pattern + ")")
      has_d = False
      # The only way to match is to at least start with what's in this pattern
      # entry.
      if not remaining_name.startswith(module_pattern):
        print(" -> module pattern start not matched")
        print("    remaining_name: " + remaining_name)
        print("    module_pattern: " + module_pattern)
        return False
      remaining_name = remaining_name[len(module_pattern):]

      # If the remaining string to match does start with this module pattern,
      # then this must either have a "/", a "_", or a "_%d" coming directly
      # after it.
      if not remaining_name[0] in ["/", "_"]:
        print(" -> module pattern not matched, looking for a seperator or index")
        print("    remaining_name: " + remaining_name)
        return False
      remaining_name = remaining_name[1:]

      # The other half of that check above, this removes all starting numbers
      # from a name (which must be the start of a module name, if we got here).
      while remaining_name[:1] in "0123456789":
        has_d = True
        remaining_name = remaining_name[1:]

      # If we had to remove a number for multiply instantiated modules then
      # we also need to remove a trailing "/"
      if has_d and not remaining_name[0] in ["/", "_"]:
        print(" -> trying to remove number, but not trailed by a speerator")
        print("    remaining_name: " + remaining_name)
        return False
      elif has_d:
        remaining_name = remaining_name[1:]

    # Strip all leading "T%d" instances from the heirarchy
    while remaining_name[:2] == "T_":
      # Chisel only generates "T_%d" nodes, not just "T" nodes.
      remaining_name = remaining_name[2:]

      if not remaining_name[:0] in "01234456789":
        print(" -> T node isn't followed by a number")
        print("    remaining_name: " + remaining_name)
        return False

      while remaining_name[:1] in "0123456789":
        remaining_name = remaining_name[1:]

      # At this point there must be another heirarchy break, otherwise this
      # wasn't a Chisel temporary.
      if not remaining_name[0] in ["/", "_"]:
        print(" -> no break after T node")
        print("    remaining_name: " + remaining_name)
        return False
      remaining_name = remaining_name[1:]

    # SRAM macros can end in an arbitrary number of "sram%d" instances towards
    # the end.
    while (remaining_name[:4] == "sram"):
      remaining_name = remaining_name[4:]
      if not remaining_name[:0] in "0123456789":
        print(" -> SRAM without number")
        print("    remaining_name: " + remaining_name)
        return False

      while len(remaining_name) > 0 and remaining_name[0] in "0123456789":
        remaining_name = remaining_name[1:]

      if len(remaining_name) is 0:
        print(" -> match OK")
        return True

      if not remaining_name[0] in ["/", "_"]:
        print(" -> SRAM number, but then no heirarchy break")
        print("    remaining_name: " + remaining_name)
        return False

      remaining_name = remaining_name[1:]

    # The new Chisel stuff calls these "ext_mem_%d" instead of SRAM, but it's
    # pretty much the same thing, but now there are two trailing numbers
    # instead of one.
    while (remaining_name[:7] == "ext_mem"):
      remaining_name = remaining_name[7:]

      if not remaining_name[:0] in "_":
        print(" -> SRAM ext_mem?, not ext_mem_")
        print("    remaining_name: " + remaining_name)
        return False
      remaining_name = remaining_name[1:]

      if not remaining_name[:0] in "0123456789":
        print(" -> SRAM without number")
        print("    remaining_name: " + remaining_name)
        return False

      while len(remaining_name) > 0 and remaining_name[0] in "0123456789":
        remaining_name = remaining_name[1:]

      if len(remaining_name) is 0:
        print(" -> match OK")
        return True

      if not remaining_name[:0] in "_":
        print(" -> SRAM ext_mem?, not ext_mem_")
        print("    remaining_name: " + remaining_name)
        return False
      remaining_name = remaining_name[1:]

      if not remaining_name[:0] in "0123456789":
        print(" -> SRAM without number")
        print("    remaining_name: " + remaining_name)
        return False

      while len(remaining_name) > 0 and remaining_name[0] in "0123456789":
        remaining_name = remaining_name[1:]

      if len(remaining_name) is 0:
        print(" -> match OK")
        return True

      if not remaining_name[0] in ["/", "_"]:
        print(" -> SRAM number, but then no heirarchy break")
        print("    remaining_name: " + remaining_name)
        return False

      remaining_name = remaining_name[1:]

    print(" -> some name remains at the end")
    print("    remaining_name: " + remaining_name)
    return False

  # These macros are used by the placement code to figure out where to place
  # things relative to this code.
  def tl(self):
    return Position(self, "tl")
  def bl(self):
    return Position(self, "bl")
  def tr(self):
    return Position(self, "tr")
  def br(self):
    return Position(self, "br")
  def json_type(self):
    return "macro"

  def __lt__(self, them):
    return self.name < them.name

# A special case macro that represents the top of the current design.
class TopMacro:
  def __init__(self, name, width, height):
    self.name = name
    self.children = []
    self.width = width
    self.height = height

  def tl(self):
    return Position(self, "tl")
  def bl(self):
    return Position(self, "bl")
  def tr(self):
    return Position(self, "tr")
  def br(self):
    return Position(self, "br")
  def tlf(self):
    return FixedPosition(self.tl())
  def blf(self):
    return FixedPosition(self.bl())
  def trf(self):
    return FixedPosition(self.tr())
  def brf(self):
    return FixedPosition(self.br())
  def json_type(self):
    return "cell"

# This is a helper method to place macros.  It's kind of like fold_left, but it
# doesn't reduce (and instead returns an array).
def chain_left(initial_value, array, func):
  prev = initial_value
  out = []
  i = 0
  for cur in array:
    out.append(func(prev, cur, i))
    prev = cur
    i = i + 1
  return out

# FIXME: The sizes here are all hard-coded while I figure out what the right
# thing to do is.
def left2right_along_top_first(prev, cur, i):
  if (i == 0):
    return Constraint(cur.tl(), prev.tr(), 20, -20, "N")
  else:
    return Constraint(cur.tl(), prev.tr(), 3, 0, "N")
def left2right_along_bot_first(prev, cur, i):
  if (i == 0):
    return Constraint(cur.bl(), prev.br(), 20, 20, "S")
  else:
    return Constraint(cur.bl(), prev.br(), 3, 0, "S")
def left2right_along_top_rest(prev, cur, i):
  if (i == 0):
    return Constraint(cur.tl(), prev.tr(), 0, -3, "N")
  else:
    return Constraint(cur.tl(), prev.tr(), 3, 0, "N")
def left2right_along_bot_rest(prev, cur, i):
  if (i == 0):
    return Constraint(cur.bl(), prev.br(), 0, 3, "S")
  else:
    return Constraint(cur.bl(), prev.br(), 3, 0, "S")

# FIXME: These are broken now
def top2bottom_along_right(prev, cur, i):
  if (i == 0):
    return Constraint(cur.tr(), prev.br(), 3, 0)
  else:
    return Constraint(cur.tr(), prev.br(), 0, -3)
def right2left_along_top(prev, cur, i):
  if (i == 0):
    return Constraint(cur.tr(), prev.tl(), 0, -3)
  else:
    return Constraint(cur.tr(), prev.tl(), -3, 0)

# Some simple placement strategies: these place macros in order, inside the
# bounds of another macro, and 
class TopLeftPlacer:
  def __init__(self, outer, anchor, macros, corner):
    self.outer = outer
    self.anchor = anchor
    self.macros = macros
    self.func = left2right_along_top_rest
    if corner == True:
      self.func = left2right_along_top_first

  def place2d(self):
    # We want roughly even rows.  This will produce exactly even rows if given
    # macros that are all the same size, otherwise it'll do something a bit
    # odder.
    width_sum = sum(map(lambda m: m.width + 3, self.macros))
    rows = ceil(width_sum / self.outer.width) + 0.0001
    row_width = width_sum / rows
    rows = []
    row = []
    row_y = 0

    # Orders the macros
    for macro in self.macros:
      row.append(macro)
      row_y = row_y + macro.width + 3
      if row_y > row_width:
        rows.append(row)
        row = []
        row_y = 0

    if len(row) > 0:
      rows.append(row)

    return rows

  def place(self):
    anchor = self.anchor
    out = []
    func = self.func
    for row in self.place2d():
      placed = chain_left(anchor, row, func)
      for place in placed:
        out.append(place)
      anchor = FixedPosition(row[0].bl())
      func = left2right_along_top_rest
    return out

  def bl(self):
    rows = self.place2d()
    if len(rows) == 0:
      return FixedPosition(self.anchor.bl())
    return FixedPosition(rows[len(rows) - 1][0].bl())

class BottomLeftPlacer:
  def __init__(self, outer, anchor, macros, corner):
    self.outer = outer
    self.anchor = anchor
    self.macros = macros
    self.func = left2right_along_bot_rest
    if corner == True:
      self.func = left2right_along_bot_first

  def place2d(self):
    # We want roughly even rows.  This will produce exactly even rows if given
    # macros that are all the same size, otherwise it'll do something a bit
    # odder.
    width_sum = sum(map(lambda m: m.width + 3, self.macros))
    rows = ceil(width_sum / self.outer.width) + 0.0001
    row_width = width_sum / rows
    rows = []
    row = []
    row_y = 0

    # Orders the macros
    for macro in self.macros:
      row.append(macro)
      row_y = row_y + macro.width + 3
      if row_y > row_width:
        rows.append(row)
        row = []
        row_y = 0

    if len(row) > 0:
      rows.append(row)

    return rows

  def place(self):
    anchor = self.anchor
    out = []
    func = self.func
    for row in self.place2d():
      placed = chain_left(anchor, row, func)
      for place in placed:
        out.append(place)
      anchor = FixedPosition(row[0].tl())
      func = left2right_along_bot_rest
    return out

  def tl(self):
    rows = self.place2d()
    if len(rows) == 0:
      return FixedPosition(self.anchor.tl())
    return FixedPosition(rows[len(rows) - 1][0].tl())

###############################################################################
# Macro Placement Schemes
###############################################################################
placement_schemes = []

# Knows how to place a single Rocket tile, without any L2 cache.
class RocketTilePlacer:
  def __init__(self, config):
    self.top = None
    self.l1dd = []
    self.l1dm = []
    self.l1id = []
    self.l1im = []

  def insert(self, macro):
    if macro.matches(config.rtl_top):
      self.top = TopMacro(macro.name, macro.width, macro.height)
    # Version Break
    elif macro.matches("coreplex/RocketTile/DCache/data"):
      self.l1dd.append(macro)
    elif macro.matches("coreplex/RocketTile/DCache/MetadataArray"):
      self.l1dm.append(macro)
    elif macro.matches("coreplex/RocketTile/icache/icache"):
      self.l1id.append(macro)
    elif macro.matches("coreplex/RocketTile/icache/icache/tag_array/tag_array"):
      self.l1im.append(macro)
    # Version Break
    elif macro.matches("coreplex/rocketTiles/dcache/data"):
      self.l1dd.append(macro)
    elif macro.matches("coreplex/rocketTiles/dcache/MetadataArray"):
      self.l1dm.append(macro)
    elif macro.matches("coreplex/rocketTiles/frontend/icache"):
      self.l1id.append(macro)
    elif macro.matches("coreplex/rocketTiles/frontend/icache/u"):
      self.l1id.append(macro)
    elif macro.matches("coreplex/rocketTiles/frontend/icache/tag_array/tag_array"):
      self.l1im.append(macro)
    else:
      print("%s cannot be matched" % macro.name)
      return False
    return True

  def list_constraints(self):
    l1dd = TopLeftPlacer   (self.top, self.top.tlf(), sorted(self.l1dd), True)
    l1dm = TopLeftPlacer   (self.top, l1dd.bl(),      sorted(self.l1dm), False)
    l1id = BottomLeftPlacer(self.top, self.top.blf(), sorted(self.l1id), True)
    l1im = BottomLeftPlacer(self.top, l1id.tl(),      sorted(self.l1im), False)
    return l1dd.place() + l1dm.place() + l1id.place() + l1im.place()

placement_schemes.append(RocketTilePlacer)

# Knows how to place a single BOOM tile, which has more branch predictor state
# in SRAMs than Rocket does.
class BoomTilePlacer(RocketTilePlacer):
  def __init__(self, config):
    self.top = None
    self.l1dd = []
    self.l1dm = []
    self.l1id = []
    self.l1im = []
    self.l1ht = []
    self.l1pt = []
    self.l1ei = []

  def insert(self, macro):
    if macro.matches(config.rtl_top):
      self.top = TopMacro(macro.name, macro.width, macro.height)
    # Version Break
    elif macro.matches("coreplex/BOOMTile/DCache/data"):
      self.l1dd.append(macro)
    elif macro.matches("coreplex/BOOMTile/DCache/MetadataArray"):
      self.l1dm.append(macro)
    elif macro.matches("coreplex/BOOMTile/HellaCache/MetadataArray"):
      self.l1dm.append(macro)
    elif macro.matches("coreplex/BOOMTile/HellaCache/meta"):
      self.l1dm.append(macro)
    elif macro.matches("coreplex/BOOMTile/icache/icache"):
      self.l1id.append(macro)
    elif macro.matches("coreplex/BOOMTile/icache/icache/u"):
      self.l1id.append(macro)
    elif macro.matches("coreplex/BOOMTile/HellaCache/data"):
      self.l1dd.append(macro)
    elif macro.matches("coreplex/BOOMTile/icache/icache/tag_array/tag_array"):
      self.l1im.append(macro)
    elif macro.matches("coreplex/BOOMTile/core/bpd_stage/br_predictor/counters/p_table/p_table/p_table"):
      self.l1pt.append(macro)
    elif macro.matches("coreplex/BOOMTile/core/bpd_stage/br_predictor/counters/h_table/h_table/h_table"):
      self.l1ht.append(macro)
    elif macro.matches("coreplex/BOOMTile/core/bpd_stage/br_predictor/brob/entries_info/entries_info"):
      self.l1ei.append(macro)
    else:
      print("%s cannot be matched" % macro.name)
      return False
    return True

  def list_constraints(self):
    l1dd = TopLeftPlacer   (self.top, self.top.tlf(), sorted(self.l1dd), True)
    l1dm = TopLeftPlacer   (self.top, l1dd.bl(),      sorted(self.l1dm), False)
    l1ht = BottomLeftPlacer(self.top, self.top.blf(), sorted(self.l1ht), True)
    l1pt = BottomLeftPlacer(self.top, l1ht.tl(),      sorted(self.l1pt), False)
    l1id = BottomLeftPlacer(self.top, l1pt.tl(),      sorted(self.l1id), False)
    l1im = BottomLeftPlacer(self.top, l1id.tl(),      sorted(self.l1im), False)
    l1ei = BottomLeftPlacer(self.top, l1im.tl(),      sorted(self.l1ei), False)
    return l1dd.place() + l1dm.place()  + l1ht.place() + l1pt.place() + l1id.place() + l1im.place() + l1ei.place()

placement_schemes.append(BoomTilePlacer)

###############################################################################
# Driver Code
###############################################################################
parser = ArgumentParser("Generate a floorplan from a macro list")
parser.add_argument('--rtl_top', dest='rtl_top', type=str, required=True)
parser.add_argument('--macros', dest='macros_filename', type=str, required=True)
parser.add_argument('--config', dest='config', type=str, required=True)
parser.add_argument('-o', dest='output_floorplan_filename', type=str, required=True)

config = parser.parse_args()

best_placer = None
best_placed = 0
for p in placement_schemes:
  placer = p(config)
  n_placed = 0
  for line in open(config.macros_filename, "r").readlines():
    if placer.insert(ParsedMacro(line)):
      n_placed = n_placed + 1
  if n_placed > best_placed:
    best_placed = n_placed
    best_placer = p

print("Using " + best_placer.__name__ + " to place design")
placer = best_placer(config)
for line in open(config.macros_filename, "r").readlines():
  if not placer.insert(ParsedMacro(line)):
    print("Unable to place design")
    exit(1)

c_json = map( (lambda constraint: constraint.as_json()), placer.list_constraints())
json = '[ %s ]' % (',\n'.join(c_json))
fp_out = open(config.output_floorplan_filename, "w")
print(json, file=fp_out)
