#!/bin/bash

set -e
set -o pipefail
set -x

unset lef
unset output
unset milkyway
unset tf
while [[ "$1" != "" ]]
do
    case "$1"
    in
    "$0");;
    *.lef) lef+=("$1");;
    -o) output="$2";shift;;
    */Milkyway) milkyway="$1";;
    *.tf) tf+=("$1");;
    *)          echo "Unknown argument $1"; exit 1;;
    esac

    shift
done

if [[ "$output" == "" || "$lef" == "" || "$milkyway" == "" ]] 
then
    echo "missing argument" >&2
    exit 2
fi

final_library_name="$(basename $lef .lef)"
mkdir -p $(dirname $output)
full_output_path="$(readlink -f $(dirname $output))"
cell_name=$(echo "$final_library_name" | cut -d_ -f1 | tr '[:lower:]' '[:upper:]')
edif_name="$final_library_name".edif
db_name="$final_library_name".db
tf_name="$final_library_name".tf

tempdir="$(mktemp -d /tmp/plsi-lef2mw.XXXXXX)"
trap "rm -rf $tempdir" EXIT

cat > $tempdir/extend_mw_layers.tcl <<EOF
extend_mw_layers
EOF

cat > $tempdir/generate_mw.scm << EOF
source "extend_mw_layers.tcl"
cmCreateLib
setFormField "Create Library" "Library Name" "$final_library_name"
setFormField "Create Library" "Technology File Name" "$tf"
setFormField "Create Library" "Set Case Sensitive" "1"
formOK "Create Library"
geOpenLib
formButton "Open Library" "browse..."
setFormField "Open Library" "Library Name" "$final_library_name"
formOK "Open Library"
read_lef
formButton "Read LEF" "browse..."
setFormField "Read LEF" "Library Name" "$final_library_name"
setFormField "Read LEF" "Cell LEF Files" "$(readlink -f $lef)"
formOK "Read LEF"
cmDumpTech
setFormField "Dump Technology File" "Technology File Name" "$tf_name"
formOK "Dump Technology File"
auEdifOut
setFormField "Edif Out" "Cell Name" "$cell_name"
setFormField "Edif Out" "Library Name" "$final_library_name"
setFormField "Edif Out" "Edif File Name" "$edif_name"
formOK "Edif Out"
exit
EOF
cd $tempdir
echo "" | flock -x $HOME/.mw.lock $milkyway -nullDisplay -nogui -load generate_mw.scm

find

cp -a --reflink=auto $final_library_name/* $full_output_path
