#!/bin/bash

script_dir="$(dirname "$0")"
source "$script_dir/icc_common.sh"

# Here's the actual ICC invocation
cd $run_dir
make -f rm_setup/Makefile_zrt init_design_icc -j1 |&
	tee icc.log
touch reports/all_macros.out
icc_shell -64bit -f generated-scripts/list_macros.tcl |&
	tee icc-list_macros.log

# Make sure there's no invalid output from ICC
cat icc.log | grep ^Warning && (echo "ICC produced warning messages")
cat icc.log | sed 's@^Error Summary@Summary of Errors@' | grep ^Error && (echo "ICC produced error messages"; exit 1)

grep ^Warning icc-list_macros.log && (echo "ICC produced warning messages")
grep ^Error icc-list_macros.log && (echo "ICC produced error messages"; exit 1)
exit 0
