#!/bin/bash
# Lightweight wrapper around make + tee

unset run_dir
while [[ "$1" != "" ]]
do
    case "$1" in
    "$0") ;;
    --run_dir) run_dir="$2"; shift;;
    *) echo "Unknown argument $1"; exit 1;;
    esac
    shift
done

source "$run_dir"/enter

make -f rm_setup/Makefile_zrt ic -j1 |& tee icc.log

# Make sure there's no invalid output from ICC
grep ^Warning icc.log && (echo "ICC produced warning messages")
grep ^Error icc.log && (echo "ICC produced error messages"; exit 1)
exit 0
