#!/bin/bash

set -ex

unset dc_dir
unset formality

while [[ "$1" != "" ]]
do
    case "$1" in
    --dc-dir) dc_dir="$2"; shift;;
    */fm_shell) formality="$1";;
    *) echo "Unknown argument $1"; exit 1;;
    esac
    shift
done

# Use the Sysnopsys's Formality script
cd $dc_dir
cp rm_dc_scripts/fm.tcl generated-scripts/verify.tcl

# FIXME: The Synopsys 32nm EDK seems to have some missing references, this
# ignores them.
sed 's/\(\s*\)#\(\s*\)\(set_app_var hdlin_unresolved_modules black_box\)/\3/' -i generated-scripts/verify.tcl
# FIXME: This appears to come from FIRRTL
sed '/^set_app_var hdlin_unresolved_modules black_box/a set_mismatch_message_filter -suppress FMR_ELAB-147' -i generated-scripts/verify.tcl

# Run Formality
cat /dev/null | $formality -f $dc_dir/generated-scripts/verify.tcl

exit 1
