#!/bin/bash
# Run the Vivado synthesis.
# Uses the --dcp_macro_dir as the parameter for the SRAM .dcp files.
# If successful, copies the resulting output to the path specified by the --dcp
# argument.

workdir_tag="vivado"

# setup environment variables
source "$VIVADO_SETUP_SH"

script_dir="$(dirname "$0")"
source "$script_dir/vivado_common.sh"

# TODO: hack hack hack
export TOP=$top

cd $workdir

# TODO: fix simulation as well
$VIVADO_BIN $VIVADOFLAGS

if [ -n "$dcp" ]; then
    echo "--dcp specified, copying post_synth.dcp";
    cp $workdir/obj/post_synth.dcp $dcp
fi
