#!/bin/bash

unset simulator
unset debug
unset vcd
args=()
while [[ "$1" != "" ]]
do
    case "$1" in
    */simulator-debug)
        simulator="$1"
        debug="true"
        ;;
    */simulator-ndebug)
        simulator="$1"
        debug="false"
        ;;
    */ptest) ;;
    --vcd) vcd="$2"; shift;;
    "$0") ;;
    *) args+=("$1");;
    esac
    shift
done

debug_args=()
if [[ "$debug" == "true" ]]
then
    debug_args+=("-v${vcd}")
fi

set -x
"$simulator" \
    ${debug_args[*]} \
    ${args[*]}
