name: hammer-pr-ci

on:
  push:
    branches:
      - packaging-actions
  pull_request:
    branches:
      - packaging
      - master

jobs:
  poetry-jobs:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    outputs:
      pytestOutput: ${{ steps.1.outputs.test }}
      mypyOutput: ${{ steps.2.outputs.test }}
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]
        experimental: [true]
    steps:
      - name: Checkout the Current Repository
        uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Use Poetry Actions to Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Check existance of pyproject.toml file
        uses: andstor/file-existence-action@v1
        with:
          files: "pyproject.toml"
      - name: Download required dependencies using poetry
        run: |
          poetry config virtualenvs.in-project true
          poetry install
      - name: Run pytests using poetry
        id: 1
        run: |
          poetry run pytest tests/ -v
      - name: Type checking
        id: 2
        run: |
          touch .venv/lib/python3.10/site-packages/ruamel/py.typed
          poetry run mypy --namespace-packages -p hammer
  pypijob:
    runs-on: ubuntu-latest
    steps:
      - name: You made it!
        run: |
          ls -a
