name: run-sh-test
on: [pull_request, push]
env:
  HAMMER_HOME: $PWD



jobs:
    checkout:
      runs-on: ubuntu-latest #Switch to redhat 7
      steps:
        - name: Setup_for_Repository
          uses: actions/checkout@v2
        - name: Check Current Repository
          run: ls
    bash_initial_setup:
      runs-on: ubuntu-latest
      needs: [checkout] 
      strategy:
        matrix:
          python-version: [3.5, 3.6, 3.7, 3.8, 3.9] 
          #Version 3.4 not on x64, so skipping 3.4 for now.
          os: [ubuntu-latest] #add red hat 7 here
      steps:
        - if: 3.4 == ${{matrix.python-version}}
          run: |
            python3 -m pip install typing
            python3 -m pip install enum34
        - name: Set Up Python ${{ matrix.python-version }} #Here, I can use strategy but should I? Is only the most relevant python version okay (if we need pre 3.4, further setup needed)
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install pytest
          run: |
            python -m pip install --upgrade pip
            pip install pytest
        - name: source_setup
          run: |
            ls
            source sourceme.sh
        - name: script
          run: |
            cd $GITHUB_WORKSPACE/src/test
            ./unittests.sh
            echo $?
#    bash_setup_check:
#     runs-on: ubuntu-latest
#      needs: [checkout, bash_initial_setup]
#      env:
#         HAMMER_HOME: $HOME
#      strategy:
#        matrix:
#          python-version: [3.6, 3.7, 3.8, 3.9]
#      steps:
 #       - name: git_submodule
  #        run: |
  #          git submodule update --init --recursive
  #      - name: source_and_cd
   #       run: |
    #        source sourceme.sh
      #      cd src
    #    - name: tests
     #     run: |
     #       ./unittests.sh
      #      echo $?