#!/bin/bash
# Script to build the config and run all necessary processing (rectifying, metadata processing).
# Requirements:
# Export OBJ_CONFIG_DB to environment
# Export OBJ_CONFIG_DIR to environment
# Export OBJ_CONFIG_BITS_DIR to environment
# Export PLSI_CMD_YAML2JSON to environment
# Export PLSI_CMD_RECTIFY_PATH to environment
# Export PLSI_CMD_EXECUTE_CONFIG_META to environment
# $(CMD_PYTHON3) in PATH

if [[ -z "$OBJ_CONFIG_DB" ]]; then
	>&2 echo "Must export OBJ_CONFIG_DB"
	exit 1
fi

if [[ -z "$OBJ_CONFIG_DIR" ]]; then
	>&2 echo "Must export OBJ_CONFIG_DIR"
	exit 1
fi

if [[ -z "$OBJ_CONFIG_BITS_DIR" ]]; then
	>&2 echo "Must export OBJ_CONFIG_BITS_DIR"
	exit 1
fi

if [[ -z "$PLSI_CMD_YAML2JSON" ]]; then
	>&2 echo "Must export PLSI_CMD_YAML2JSON"
	exit 1
fi

if [[ -z "$PLSI_CMD_RECTIFY_PATH" ]]; then
	>&2 echo "Must export PLSI_CMD_RECTIFY_PATH"
	exit 1
fi

if [[ -z "$PLSI_CMD_EXECUTE_CONFIG_META" ]]; then
	>&2 echo "Must export PLSI_CMD_EXECUTE_CONFIG_META"
	exit 1
fi

if [[ -z "$(which python3)" ]]; then
	>&2 echo "Must have CMD_PYTHON3 in PATH"
	exit 1
fi

mkdir -p $OBJ_CONFIG_DIR
mkdir -p $OBJ_CONFIG_BITS_DIR

unset config_files; config_files=()
while [[ "$1" != "" ]]
do
    case "$1" in
    "$0") ;;
    *.yml) config_files+=("$1");;
    *.json) config_files+=("$1");;
    *) echo "Unknown argument $1 - not yml or json"; exit 1;;
    esac
    shift
done

set -ex

targets=()

for config_file in "${config_files[@]}"; do
	fullname=$(readlink -f ${config_file})
	second_last_name=$(basename $(dirname ${fullname}))
	if [[ "$config_file" == *.yml ]]; then
		# Hopefully this is disambiguous enough...
		tag="${second_last_name}_$(basename ${fullname} .yml)"
		target=${OBJ_CONFIG_DIR}/${tag}.yml.json
	elif [[ "$config_file" == *.json ]]; then
		tag="${second_last_name}_$(basename ${fullname} .json)"
		target=${OBJ_CONFIG_DIR}/${tag}.json
	else
		>&2 echo "Unknown extension for $config_file - not yml or json"
	fi

	./src/tools/build-config "${targets[@]}" > ${OBJ_CONFIG_DIR}/pre_${tag}.json
	echo "Built by PLSI from src/tools/build-config ${targets[@]}" > ${OBJ_CONFIG_DIR}/pre_${tag}.json.meta
	if [[ "$config_file" == *.yml ]]; then
		${PLSI_CMD_YAML2JSON} ${config_file} ${target}
		${PLSI_CMD_RECTIFY_PATH} --prefix $(dirname $(readlink -f $config_file)) --in-place ${target}
		${PLSI_CMD_EXECUTE_CONFIG_META} --srcdir $(dirname $(readlink -f $config_file)) --outdir ${OBJ_CONFIG_BITS_DIR} --globaldb ${OBJ_CONFIG_DIR}/pre_${tag}.json --in-place ${target}
	elif [[ "$config_file" == *.json ]]; then
		cp ${config_file} ${target}
		${PLSI_CMD_RECTIFY_PATH} --prefix $(dirname $(readlink -f $config_file)) --in-place ${target}
		${PLSI_CMD_EXECUTE_CONFIG_META} --srcdir $(dirname $(readlink -f $config_file)) --outdir ${OBJ_CONFIG_BITS_DIR} --globaldb ${OBJ_CONFIG_DIR}/pre_${tag}.json --in-place ${target}
	else
		>&2 echo "Unknown extension for $config_file - not yml or json"
	fi

	targets+=("${target}")
done

./src/tools/build-config "${targets[@]}" > ${OBJ_CONFIG_DB}
echo "Built by PLSI from src/tools/build-config ${targets[@]}" > ${OBJ_CONFIG_DB}.meta
