#!/bin/bash
# Build list of '-f' Makefiles.
# e.g. "file1 file2" -> "-f file1 -f file2"
makefiles=""
IFS=" "
arr_buf="$@"
while true; do
 read -r file rest <<< $arr_buf
  if [ ! -z "$file" ]; then
    makefiles="$makefiles -f $file";
  fi
  arr_buf=${rest}
  if [ -z "$arr_buf" ]; then
    break
  fi
done
echo -n "${makefiles}"
